use crate::graphics::{PIXOFF, PIXON};

pub type Sprite = [[char; 5]; 5];
const ZERO: Sprite = [
    [PIXON, PIXON, PIXON, PIXON, PIXON],
    [PIXON, PIXOFF, PIXOFF, PIXOFF, PIXON],
    [PIXON, PIXOFF, PIXOFF, PIXOFF, PIXON],
    [PIXON, PIXOFF, PIXOFF, PIXOFF, PIXON],
    [PIXON, PIXON, PIXON, PIXON, PIXON],
];

const ONE: Sprite = [
    [PIXOFF, PIXOFF, PIXON, PIXOFF, PIXOFF],
    [PIXOFF, PIXON, PIXON, PIXOFF, PIXOFF],
    [PIXOFF, PIXOFF, PIXON, PIXOFF, PIXOFF],
    [PIXOFF, PIXOFF, PIXON, PIXOFF, PIXOFF],
    [PIXOFF, PIXON, PIXON, PIXON, PIXOFF],
];

const TWO: Sprite = [
    [PIXOFF, PIXON, PIXON, PIXON, PIXOFF],
    [PIXOFF, PIXOFF, PIXOFF, PIXON, PIXOFF],
    [PIXOFF, PIXON, PIXON, PIXON, PIXOFF],
    [PIXOFF, PIXON, PIXOFF, PIXOFF, PIXOFF],
    [PIXOFF, PIXON, PIXON, PIXON, PIXOFF],
];

const THREE: Sprite = [
    [PIXOFF, PIXON, PIXON, PIXON, PIXOFF],
    [PIXOFF, PIXOFF, PIXOFF, PIXON, PIXOFF],
    [PIXOFF, PIXOFF, PIXON, PIXON, PIXOFF],
    [PIXOFF, PIXOFF, PIXOFF, PIXON, PIXOFF],
    [PIXOFF, PIXON, PIXON, PIXON, PIXOFF],
];

const FOUR: Sprite = [
    [PIXOFF, PIXOFF, PIXON, PIXOFF, PIXOFF],
    [PIXOFF, PIXON, PIXON, PIXOFF, PIXOFF],
    [PIXON, PIXOFF, PIXON, PIXOFF, PIXOFF],
    [PIXON, PIXON, PIXON, PIXON, PIXOFF],
    [PIXOFF, PIXOFF, PIXON, PIXOFF, PIXOFF],
];

const FIVE: Sprite = [
    [PIXOFF, PIXON, PIXON, PIXON, PIXOFF],
    [PIXOFF, PIXON, PIXOFF, PIXOFF, PIXOFF],
    [PIXOFF, PIXON, PIXON, PIXON, PIXOFF],
    [PIXOFF, PIXOFF, PIXOFF, PIXON, PIXOFF],
    [PIXOFF, PIXON, PIXON, PIXON, PIXOFF],
];

const SIX: Sprite = [
    [PIXOFF, PIXON, PIXON, PIXON, PIXOFF],
    [PIXOFF, PIXON, PIXOFF, PIXOFF, PIXOFF],
    [PIXOFF, PIXON, PIXON, PIXON, PIXOFF],
    [PIXOFF, PIXON, PIXOFF, PIXON, PIXOFF],
    [PIXOFF, PIXON, PIXON, PIXON, PIXOFF],
];

const SEVEN: Sprite = [
    [PIXOFF, PIXON, PIXON, PIXON, PIXOFF],
    [PIXOFF, PIXOFF, PIXOFF, PIXON, PIXOFF],
    [PIXOFF, PIXOFF, PIXOFF, PIXON, PIXOFF],
    [PIXOFF, PIXOFF, PIXOFF, PIXON, PIXOFF],
    [PIXOFF, PIXOFF, PIXOFF, PIXON, PIXOFF],
];

const EIGHT: Sprite = [
    [PIXON, PIXON, PIXON, PIXON, PIXON],
    [PIXON, PIXOFF, PIXOFF, PIXOFF, PIXON],
    [PIXON, PIXON, PIXON, PIXON, PIXON],
    [PIXON, PIXOFF, PIXOFF, PIXOFF, PIXON],
    [PIXON, PIXON, PIXON, PIXON, PIXON],
];

const NINE: Sprite = [
    [PIXOFF, PIXON, PIXON, PIXON, PIXOFF],
    [PIXOFF, PIXON, PIXOFF, PIXON, PIXOFF],
    [PIXOFF, PIXON, PIXON, PIXON, PIXOFF],
    [PIXOFF, PIXOFF, PIXOFF, PIXON, PIXOFF],
    [PIXOFF, PIXOFF, PIXOFF, PIXON, PIXOFF],
];

pub const SCORE_SPRITES: [Sprite; 10] =
    [ZERO, ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE];
